config/routes.rb
Weblog::Application.routes.draw do
  root :to => "posts#display"

  resources :posts do
    collection do
      get 'display'
      match "tag/:name", :to => "posts#tag", :as => 'by_tag_name'
    end
  end
  resources :tags, :only => [:index]
  
  resources :sessions
  match '/rss', :to => "posts#display", :defaults => {:format => 'rss'}, :as => :rss
  match '/login',   :to => "sessions#new",      :as => :login
  match '/logout',  :to => "sessions#destroy",  :as => :logout
  
  match ':page_name', :to => "static#show"
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_taggable

  translates :title, :body


  validates_presence_of :body, :title
  validates_uniqueness_of :slug
  scope :live, where(:published => true).order('posts.created_at DESC')
  scope :for_nav, where(:in_navigation => true)
  
  before_create :build_slug
  
  self.per_page = 5
  
  def to_param
    slug
  end
  
  def build_slug
    self.slug = title.parameterize
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  scope :front_page, {
    :limit => 5,
    :order => 'created_at DESC'
  }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :admin?, :navigation_items, :tweets
  rescue_from ActionController::RoutingError, :with => :record_not_found
  rescue_from ActionView::MissingTemplate, :with => :record_not_found
  
  def navigation_items
    Post.where(:published => false, :in_navigation => true)
  end

  # def tweets
  #   @tweets ||= Tweet.front_page
  # end
  
  def admin_required
    unless admin?
      flash[:error] = "You must be logged in to access this page."
      redirect_to new_session_path
    end
  end

  def admin?
    session[:password] == Digest::MD5.hexdigest(ENV['ADMIN_PASS'] || 'password')
  end
  
  def record_not_found
    render "static/404"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :admin_required, :only => [ :index, :new, :edit, :create, :destroy, :update ]
  before_filter :get_resource, :only => [:show, :edit, :destroy, :update]
  def display
    @posts = Post.live.paginate(:page => params[:page])
    
    respond_to do |format| 
      format.html
      format.rss{ redirect_if_direct_request }
    end 
  end
  
  def index
    @posts = Post.order('posts.created_at DESC').all
  end
  
  def new
    @post = Post.new()
  end

  def create
    @post = Post.new(params['post'])
    if @post.save() 
    then redirect_to posts_path
    else redirect_to new_post_path end
  end

  def tag
    @posts = Post.live.tagged_with(params[:name]).paginate(:page => params[:page])
    render :display
  end
  
  def edit
  end

  def update
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @post.delete()
    redirect_to posts_path
  end

  private 
    def redirect_if_direct_request
      unless request.env['HTTP_USER_AGENT'] =~ /feedburner/i 
        redirect_to 'http://feeds.feedburner.com/AustinFlores' and return
      end 
    end

    def get_resource
      @post = Post.where(:slug => params[:id]).first
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController  
  def create  
    session[:password] = Digest::MD5.hexdigest(params[:password])
    if admin?
      redirect_to posts_path, :notice => t('sign_in.success')
    else
      redirect_to login_path, :notice => t('sign_in.bad_password')
    end
  end  
    
  def destroy  
    reset_session
    redirect_to root_path, :notice => t('sign_in.signed_out')
  end  
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def show
    render :action => params[:page_name]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.find(:all,:conditions => ['name LIKE ?', "#{params[:q]}%"], :select => :name, :order => 'name')
    respond_to do |format| 
      format.html
      format.json{ render :json => @tags.map(&:name).to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def linkify(text)
    return text if anchor_exists text
    text.gsub(/(http:\/\/[^\s]*)/,'<a href="\1" target="_blank">\1</a>')
  end

  def linkify_tweet text
    text = linkify text
    text.gsub(/@([a-zA-Z\_]+)/, '<a href="http://twitter.com/#!/\1">@\1</a>')
  end

  def anchor_exists text
    not text[/<a[^>]*>/].nil?
  end

end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/layouts/_admin_nav.html.haml
%li 
  %h4= t('nav.admin')
  %ul
    %li
      %a{:href => '/posts/'}= t('nav.manage')

app/views/layouts/_dynamic_nav.html.haml
- items.each do |item|
  %li
    =link_to t("nav.#{item.slug.downcase}"), item

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :name => "author",      :content => "Austin Flores" }
    %meta{ :name => "keywords",    :content => "Austin Flores, Ctrl4ltdeleteme, portfolio, blog" }
    %meta{ :name => "description", :content => "A blog about anything that interests me.  Typically, it will involve: Ruby, Rails, programming in general, or whatever I happen to be doing at the moment." }
    %meta{ :'http-equiv' => "Content-Type", :content=>"text/html; charset=utf-8" }
    %meta{ :name => "google-site-verification", :content => "LVaZcDWC-XvEg2q_GnbnMdCd04kcl230qQswuv2Rk2M" }
    %title Austin Flores - Blog
    = stylesheet_link_tag 'reset', 'application'
    = javascript_include_tag 'jquery', 'application', 'rails'
    = csrf_meta_tag
    %link{ :href => 'http://fonts.googleapis.com/css?family=IM+Fell+English', :rel => 'stylesheet', :type=>'text/css'}
  %body
    #header
      %h1=link_to "ctrl 4lt delete me", root_path
      %p#description
        =t('heading.tag_line')
        %span.author 
          Austin Flores
      %a#rss{ :href => rss_path} rss
    %hr
    %div#nav.rad20
      %ul
        %li=link_to t('nav.home'), '/'
        -if navigation_items.any?
          = render :partial => 'layouts/dynamic_nav', :locals => { :items => navigation_items}
        - if admin?
          = render :partial => 'layouts/admin_nav'
        %li=link_to "Github", 'http://github.com/unflores'
    %p= flash[:message]

    #wrapper
      #content_body.rad20
        %h2= if yield(:content_title).blank? then t('nav.home') else yield :content_title end
        = yield

      #foot_wrapper
        #foot_body
          %p#footer
            != t('credits')
    #twitter
      /= render :partial => 'layouts/tweet_stream', :locals => { :tweets => tweets}
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-20366055-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/posts/_post.html.haml
- form_for(@post) do |f|
  %table
    %tr
      %th= f.label 'title (h3.)'
      %td= f.text_field :title
    %tr
      %td{ :colspan=>'2' }= f.text_area :body
    %tr
      %th= f.label 'in blog?'
      %td= f.check_box :published
    %tr
      %th= f.label 'in nav?'
      %td= f.check_box :in_navigation
    %tr
      %th= f.label 'Tags'
      %td= f.text_field :tag_list
  = f.submit 'Save'
  #textile_defs
    %h4 textile usage
    %ul
      %li
        \*ul
      %li
        \#ol
      %li
        code: bc..
      %li
        inline code: @codeword@

app/views/posts/display.html.haml
- if @posts.empty? 
  %p= t('posts.none')
- else
  - @posts.each do |post|
    #article
      %h3
        = link_to post.title, post
        %span.created_at
          = post.created_at.strftime("%m-%d-%Y") if post.created_at
      .content
        != RedCloth.new(post.body).to_html
      -unless post.tag_list.blank?
        =render :partial => "shared/tag_list", :locals => { :tag_list => post.tag_list }
  = will_paginate @posts, :page_links => false

app/views/posts/edit.html.haml
%h3 Editing post

= render :partial => 'post'

= render :partial => 'shared/admin_links'

app/views/posts/index.html.haml
%p.new_post
  =link_to "+ New Post", new_post_path
%h3 Listing posts

-if @posts.any?
  %table
    %tr
      %th{:scope=>'col'} Title
      %th{:scope=>'col'} Options
      %th{:scope=>'col'} In Blog?
    - @posts.each do |post|
      %tr
        %td= link_to post.title, edit_post_path(post)
        %td
          = link_to 'Edit', edit_post_path(post), :class=>'edit', :title=>'edit'
          = link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete, :class=>'destroy', :title=>'delete'
        %td
          -if post.published
            %span.live{:title=>'yes'} yes
-else
  %p There are currently no posts. Why not #{link_to "create", new_post_path} one?

app/views/posts/new.html.haml
%h3 New post
-if @post.errors.any?
  #errors
    %p= "#{pluralize(@post.errors.count, "error")}  prohibited this user from being saved:"
    %ul  
      -@post.errors.full_messages.each do |msg|
        %li= msg
= render :partial => 'post'

= render :partial => 'shared/admin_links'

app/views/posts/show.html.haml
%h3 
	= h @post.title

%div
	!= RedCloth.new(@post.body).to_html

-if admin?
	%div 
		= link_to 'Edit this post', edit_post_path(@post)
		|
		= link_to 'Show Posts', posts_path

app/views/shared/_admin_links.html.haml
%p
  = link_to 'Show Site', root_path
  |
  = link_to 'Back to Posts', posts_path

app/views/shared/_tag_list.html.haml
.tag_list
  %span Tags:
  -tag_list.each do |name|
    %span.name
      =link_to name, by_tag_name_posts_path(:name => name)

app/views/tweets/_tweet.html.haml
.status
  %p!=linkify_tweet tweet.status
  %span.date="posted #{time_ago_in_words tweet.twitter_created_at} ago"